language: python

python:
    - "3.6"

install:
    - pip install .
    - pip install paver
    - pip install scipy
    - pip install numpy
    - pip install matplotlib
    - pip install h5py
    
script: 
    - paver
    